//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *DNSChallengeConfig) DeepCopyInto(out *DNSChallengeConfig) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	if in.PropagationSeconds != nil {
		in, out := &in.PropagationSeconds, &out.PropagationSeconds
		*out = new(int)
		**out = **in
	}
}

func (in *DNSChallengeConfig) DeepCopy() *DNSChallengeConfig {
	if in == nil {
		return nil
	}
	out := new(DNSChallengeConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

func (in *SSLConfig) DeepCopyInto(out *SSLConfig) {
	*out = *in
	in.DNSChallenge.DeepCopyInto(&out.DNSChallenge)
}

func (in *SSLConfig) DeepCopy() *SSLConfig {
	if in == nil {
		return nil
	}
	out := new(SSLConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *Npmko) DeepCopyInto(out *Npmko) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *Npmko) DeepCopy() *Npmko {
	if in == nil {
		return nil
	}
	out := new(Npmko)
	in.DeepCopyInto(out)
	return out
}

func (in *Npmko) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NpmkoList) DeepCopyInto(out *NpmkoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Npmko, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *NpmkoList) DeepCopy() *NpmkoList {
	if in == nil {
		return nil
	}
	out := new(NpmkoList)
	in.DeepCopyInto(out)
	return out
}

func (in *NpmkoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NpmkoSpec) DeepCopyInto(out *NpmkoSpec) {
	*out = *in
	if in.ServiceSelector != nil {
		in, out := &in.ServiceSelector, &out.ServiceSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DomainNames != nil {
		in, out := &in.DomainNames, &out.DomainNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(SSLConfig)
		(*in).DeepCopyInto(*out)
	}
}

func (in *NpmkoSpec) DeepCopy() *NpmkoSpec {
	if in == nil {
		return nil
	}
	out := new(NpmkoSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NpmkoStatus) DeepCopyInto(out *NpmkoStatus) {
	*out = *in
}

func (in *NpmkoStatus) DeepCopy() *NpmkoStatus {
	if in == nil {
		return nil
	}
	out := new(NpmkoStatus)
	in.DeepCopyInto(out)
	return out
}
