{{- if not .Values.npm.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: npmko-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "npmk-operator.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.npm.password | b64enc | quote }}
{{- end }}
